[build]
  functions = "functions"   # Path to serverless functions
  publish = "."             # Path to frontend assets (adjust if assets are in a subfolder)
  command = ""              # Leave empty for static sites or specify build commands

[dev]
  port = 8888               # Port for local dev server
  framework = "#static"     # Set to #static for static sites

[functions]
  node_bundler = "esbuild"  # Use esbuild for optimized functions

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200              # Redirect API calls to serverless functions